name: Create and Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shc
        run: |
          sudo apt-get update
          sudo apt-get install -y shc

      - name: Compile sshin script to binary
        run: shc -r -f sshin.sh -o sshin

      - name: Package release assets
        run: |
          mkdir -p release
          cp sshin sshin-setup.sh sshin-server-setup.sh sshin-harden-ssh.sh README.md README.fa.md release/
          tar -czvf sshin-release.tar.gz -C release .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            sshin-release.tar.gz
            sshin
            sshin-setup
            sshin-server-setup.sh
            sshin-harden-ssh.sh
